### ISSUE TITLE
Add the fxa capability on the hello page.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-fxa#23]

**Comment by lavish205** [comment]
@Natim is this bug similar to [flush_endpoint capability](https://github.com/Kinto/kinto/pull/496)

**Comment by Natim** [comment]
Yes it will more or less look like that: https://github.com/Kinto/kinto-changes/pull/10

**Comment by lavish205** [comment]
ok I'll fix this

**Comment by lavish205** [comment]
@Natim In which file I have to add code? I can't see the relevant file.

**Comment by Natim** [comment]
Probably here : https://github.com/mozilla-services/cliquet-fxa/blob/master/cliquet_fxa/__init__.py#L46

**Comment by lavish205** [comment]
what will be value of `description` and `urls` in `fxa` capability?

**Comment by Natim** [comment]
```
"fxa": {
    "url": "https://github.com/mozilla-services/kinto-fxa",
    "description": "You can authenticate to that server using Firefox Account."
},
```

**Comment by lavish205** [comment]
@Natim in which test file should I include the tests?

**Comment by Natim** [comment]
Probably this one: https://github.com/mozilla-services/kinto-fxa/blob/master/kinto_fxa/tests/test_views.py

**Comment by Natim** [comment]
You could also create a new one.
