### ISSUE TITLE
Add a Makefile to ease running tests and releasing

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-fxa#24]
- [ ] build-requirements
- [ ] make tests (running with tox)
- [ ] make tests-once (running in the local venv with pytest or nose)
- [ ] make install (installing the plugin in the current venv or creating one)

**Comment by leplatrem** [comment]
Done in https://github.com/mozilla-services/kinto-fxa/commit/63dfc0301ddbff919c542856f821eb19574c9ab9
