### ISSUE TITLE
Second validation fails

### ISSUE THREAD

**Issue by glasserc** [mozilla-services/kinto-fxa#33]
My localhost dev server that I'm using to validate FxA tokens was responding normally for a while but now that I've deleted a token, it's starting to behave strangely. Requests from the client are timing out. If I restart the server, the first request will go through normally and function correctly, but the second one will time out. I've added a bunch of debugging output and it seems like it's getting stuck when it consults the cache, which is a kinto.core.cache.postgresql.Cache object.

Maybe this is related to Kinto/kinto#804? I'm running current master of everything as far as I can tell.

**Comment by glasserc** [comment]
Never mind, I think restarting postgres made it go away.

**Comment by glasserc** [comment]
No, wait, it didn't. I can reproduce this when I make a query using an invalid bearer token.

```
curl 'http://localhost:8888/v1/buckets/default/collections/augmented-search@mozilla.org/records?_sort=-last_modified&_since=1473771653605' -H "Authorization: Bearer c3601047ecd2e5b471319c7edebba5f641094a614b4d8c30c0500cd9dce596d9"
```

run twice induces it.

**Comment by Natim** [comment]
Yes it is probably related to transaction not being closed / aborted correctly :(

**Comment by Natim** [comment]
@glasserc encoutered the bug today so I will investigate closely.

**Comment by glasserc** [comment]
I paired with @Natim a little today to try to track this down more thoroughly. He wasn't able to reproduce it on his machine, but was able to see it on the dev instance that we put up for chrome.storage.sync. He said this might be due to a transaction that needs to be closed in the plugin, and that we've made changes like this in other plugins, but that he wanted to see if it were possible to defend against this issue in the Kinto codebase itself rather than having to fix every possible plugin. For this reason, we looked at the Kinto module `core.views.errors`.

At present, it seems like the control flow is something like this [N.B. all of this is guesswork and probably wrong]:

- Request comes in for `/v1/buckets/default/collections` with a "Bearer blah" token.
- Because this is a ViewSet, its permission is DYNAMIC, so it tries to identify the user.
- This calls `kinto_fxa._get_credentials`. This calls `auth_client.verify_token()`, which throws an exception, which is caught below. `_get_credentials` returns `None`.
- That `None` gets turned into a `system.Everyone`, who doesn't have permissions.
- A 403 Forbidden is raised and handled by `views.errors`. `authorization_required` checks if the user was actually authenticated; if not, it tries to raise a 401 Unauthorized instead.
- Checking who the current `effective_principals` is, causes another transaction/HTTP round trip (we only cache "successful responses"). Presumably this is the transaction that isn't getting closed.

Adding `import transaction; transaction.abort()` at the beginning of the body of this `if` statement causes the hang to go away, but it doesn't feel like the right fix. Shouldn't all transactions only last until the request is over? Why is this one special in not getting cleaned up?

One question I have is: why aren't we doing `reapply_cors` here? https://github.com/Kinto/kinto/blob/f7cd8d08fa77337a718703e6e704699fdcf34939/kinto/core/views/errors.py#L25

**Comment by Natim** [comment]
Thank you for this summary. I agree with your description.

For the reapply_cors, I guess we need to add a test to see if it is broken in that case.
We probably didn't add it because we didn't write a test failing for it.
But I get the intuition that cors is broken when we authenticate with a wrong bearer token.

I feel like aborting transaction in error is always sane but I would like to ask @leplatrem some insight about the transaction.abort at this time of the code process.

**Comment by glasserc** [comment]
@leplatrem mentioned in chat today that this would normally be handled by https://github.com/Pylons/pyramid_tm/blob/master/pyramid_tm/__init__.py#L28. Actually, it seems like the actual control flow is hitting https://github.com/Pylons/pyramid_tm/blob/master/pyramid_tm/__init__.py#L106 when the `Forbidden` response is getting called. The only problem is that this is happening before the error view runs, and that error view seems to be starting another transaction which isn't getting closed. I don't really understand why this would happen since it seems like this view is something that should happen "inside" the handler?

**Comment by glasserc** [comment]
This was eventually supplanted by #35.
