### ISSUE TITLE
Add a scoped principal

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto-fxa#51]
In the Kinto Test Pilot stack we will end-up having multiple collections for multiple projects.

People will connect using different tokens for different collection access.

My token for Notes shouldn't not all my token for lockbox to actually fetch the notes.

A way of doing that is to create principals scoped with the token scopes.

For instance a token with ``profile https://identity.mozilla.org/apps/notes`` could give the following scopes:

``[fxa:FxaID fxa:FxaID-apps-notes fxa:FxaID-profile]``

Which woud allow to give permission to ``fxa:FxaID-apps-notes`` for a collection to prevent token for ``fxa:FxaID-apps-lockbox`` to access the records.

**Comment by leplatrem** [comment]
So, you would retrieve the list of scopes, and do something like: `principals += [(userid + "-" + s) for s in scopes]`

**Comment by vladikoff** [comment]
@Natim I am getting 

```
 pyramid.exceptions.ConfigurationError: https://identity.mozilla.com/apps/notes is already required for another config.
```

with the following: 

```
fxa-oauth.clients.notesandroid.client_id = b7d74070a481bc11
fxa-oauth.clients.notesandroid.required_scope = https://identity.mozilla.com/apps/notes
fxa-oauth.clients.notes.client_id = c6d74070a481bc10
fxa-oauth.clients.notes.required_scope = https://identity.mozilla.com/apps/notes
```

I should be able to have 2 clients with the same `required_scope`, am I missing something?

**Comment by rfk** [comment]
> I should be able to have 2 clients with the same required_scope, am I missing something?

IIRC from reviewing this functionality last year, I think this is actually not supported.  Since "notes" and "notesandroid" are in the config as two different clients, it will try to segregate data for the two different clients and needs unique scopes in order to do so.

It seems like we want some notion that multiple clients can belong to the same "app" and should share data by default, perhaps based on sharing the same `required_scope`.  But the current code does't support this.

**Comment by vladikoff** [comment]
> It seems like we want some notion that multiple clients can belong to the same "app" and should share data by default, perhaps based on sharing the same required_scope.

Exactly, I thought that's what @Natim meant when he said:

> In the Kinto Test Pilot stack we will end-up having multiple collections for multiple projects.

Anyway, I hope it's not too complex to add this in. 💻 ☄️

**Comment by leplatrem** [comment]
As far as I understood the client name is suffixed to the userid, so by default the data will be isolated. Do you use the default bucket or a bucket id that depends on the userid in Notes?

I think the unsuffixed userid is also given as extra principal, so with regards to sharing the same collection with write permission, you could just add the unprefixed userid in the write permission from the JS client to allow every other clients.

**Comment by Natim** [comment]
You should use the same config in Kinto for both android and the widget since you don't need to have separate data for android and for notes because you want to share them.

**Comment by Natim** [comment]
Have you tried using your bearer token directly without changing the configuration?

**Comment by vladikoff** [comment]
> Have you tried using your bearer token directly without changing the configuration?

Yeap it works 👍 , i thought i had to create more clients. but i guess not!
